spring.application.name=QUANTITY-SERVICE
server.port=${PORT:8082}


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quantitymeasurementdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:physics123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


jwt.secretKey=${JWT_SECRET:jdhwuydhwiedhud52e5dew5dfff63f43fwefw5ffwfwfbhwjf5wwadwdbjwbdww65wwdwebjdw}


eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${HOST_IP:localhost}
eureka.instance.non-secure-port=${PORT:8082}
eureka.instance.instance-id=${spring.application.name}:${HOST_IP:localhost}:${PORT:8082}
eureka.instance.status-page-url=http://${HOST_IP:localhost}:${PORT:8082}/actuator/info
eureka.instance.health-check-url=http://${HOST_IP:localhost}:${PORT:8082}/actuator/health
eureka.instance.home-page-url=http://${HOST_IP:localhost}:${PORT:8082}/


springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


logging.level.root=INFO


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always