spring.application.name=EUREKA-SERVER
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

# Nice dashboard
eureka.instance.hostname=${EUREKA_HOST:localhost}
eureka.instance.prefer-ip-address=false

eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000